### ISSUE TITLE
VEP Annotations and FAF information for cohort studies

### ISSUE THREAD

**Issue by weewus** [KalinNonchev/gnomAD_DB#37]
Hi, it would be really helpful if VEP annotations could be included or if you had any good ideas on how to cross reference. Currently I'm having to generate vcfs for the positions I'm interested in and use ensembl's VEP annotation program.

Similarly, [Filtering Allele Frequency](https://gnomad.broadinstitute.org/help/faf) would be very useful.

**Comment by KalinNonchev** [comment]
Hi @weewus ,
thank you for your interest! Unfortunately, including VEP annotations isn't feasible because a single variant can be linked to multiple genes, complicating the database logic. Similarly, handling Filtering Allele Frequency would add complexity, making it impractical within the current system.
Please let me know if you have further comments.

Best,
Kalin

**Comment by AndreasSandJespersen** [comment]
Hey sorry, I missed this reply. Thanks for the clarification.
What about homozygous count? This isn't something that's otherwise intuitable/possible to annotate after the fact.
This would be pretty useful for recessive studies.

Cheers,
Andreas
